sigma = 0.0001;
save temp.mat sigma;
main_KS_v1;
sigma = 0.001;
save temp.mat sigma;
main_KS_v1;
sigma = 0.007;
save temp.mat sigma;
main_KS_v1;
sigma = 0.01;
save temp.mat sigma;
main_KS_v1;
sigma = 0.015;
save temp.mat sigma;
main_KS_v1;
sigma = 0.02;
save temp.mat sigma;
main_KS_v1;
sigma = 0.025;
save temp.mat sigma;
main_KS_v1;
sigma = 0.03;
save temp.mat sigma;
main_KS_v1;
sigma = 0.035;
save temp.mat sigma;
main_KS_v1;
sigma = 0.04;
save temp.mat sigma;
main_KS_v1;
sigma = 0.045;
save temp.mat sigma;
main_KS_v1;
sigma = 0.05;
save temp.mat sigma;
main_KS_v1;